Repository GlueOps/certs-backup-restore, pull requests merged in 2025-05, with the labels that each got.

#108 feat: update to boto3[crt]==1.38.8 so that s3 multi region access point works
  requirements.txt
Labels: enhancement, include-in-release-notes, Review effort 1/5, minor

#110 refactor for new backup strategy
  restore/restore.py
Labels: Review effort 3/5

#111 fixed restoring algorithm
  restore/restore.py
Labels: Review effort 2/5

#113 feat: Add PRCHECKLIST using Pull Request Checklist Buddy
  PRCHECKLIST
Labels: enhancement, include-in-release-notes, Review effort 1/5, minor

#114 fix: add exit() when error occurs
  backup/backup.py
Labels: patch, include-in-release-notes, Review effort 2/5
